apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubeopstests.neonforge.io
spec:
  group: neonforge.io
  names:
    kind: KubeOpsTest
    listKind: KubeOpsTestList
    plural: kubeopstests
    singular: kubeopstest
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Used for testing purposes.
        properties:
          status:
            properties:
              phase:
                type: string
            type: object
          spec:
            properties:
              message:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}